<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>primaryIncomeEarner</name>
   <tag></tag>
   <elementGuidId>5b0ac9fe-f121-4210-a195-af4fc4f2bf3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@formcontrolname = 'primaryIncomeEarnerEmployementDetail' and @type = 'number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control yrsField ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>primaryIncomeEarnerEmployementDetail</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/edit-application[1]/sidemenu[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10 page-wrapper&quot;]/div[@class=&quot;page-content&quot;]/form[@class=&quot;application-form form-horizontal ng-invalid ng-touched ng-dirty&quot;]/solar-scheme-edit[1]/div[@class=&quot;ng-touched ng-invalid ng-dirty&quot;]/div[@class=&quot;ng-touched ng-invalid ng-dirty&quot;]/form-field[3]/div[@class=&quot;form-group&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-2&quot;]/input[@class=&quot;form-control yrsField ng-untouched ng-pristine ng-valid&quot;]</value>
   </webElementProperties>
</WebElementEntity>
